apiVersion: apps/v1
kind: Deployment
metadata:
  name: actor
  namespace: default
  labels:
      app: actor
      cpp: actor
spec:
  replicas: 4
  selector:
    app: actor
  template:
    metadata:
      labels:
        app: actor
    spec:
      volumes:
        name: code-0
        nfs:
          path: /data/nfs/rl-framework
          server: 192.168.4.18
      containers:
        - image: zouyuan/test/framework:actor
          name: m0web
          command: ["/bin/sh","-c"]
          args: ["apt update;apt install dnsutils -y;lip=`nslookup learner.default| grep Address |grep -v '#' |awk '{print $2}'`;sed -i '/ip:/d' /zouyuan/examples/ppo/ant-v2_actor.yaml;sed -i \"4a \\ \\ ip: $lip\" /zouyuan/examples/ppo/ant-v2_actor.yaml;python /zouyuan/actor.py  --config /zouyuan/examples/ppo/ant-v2_actor.yaml;sleep 100000000"]
          resources:
            requests:
              memory: "60Gi"
              cpu: "1"
              nvidia.com/gpu: "0"
            limits:
              memory: "60Gi"
              cpu: "1"
              nvidia.com/gpu: "0"
          ports:
          - containerPort: 8080
          volumeMounts:
            name: code-0
            mountPath: /zouyuan

