apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 20000
      name: user-port
      nodePort: 30000
      targetPort: 20000
    - port: 20001
      nodePort: 30001
      name: task-port
      targetPort: 20001
