apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  namespace: default
  labels:
      app: myweb
      cpp: web
spec:
  replicas: 3
  selector:
    app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - image: docker.io/tomcat:7
          name: myweb
          command: ["/bin/sh","-c"]
          args:
          - while true;
            do echo hello;
            sleep 10;
            done;
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          ports: 
          - containerPort: 8080
        - image: ustc.mcc.com/library/myapp:v1
          name: myweb
          command: "while true;do echo hello;sleep 10;done"
          resources:
            requests:
              memory: "128Mi"
              cpu: "1000"
            limits:
              memory: "500Mi"
              cpu: "2000"
          ports:
            containerPort: 8080
